### PR TITLE
fix: preserve JSON body when CSRF token is sent in header

### LINKED ISSUE #10063: Bug: CSRF filter URL-encodes JSON request body in 4.7.1, breaking IncomingRequest::getJSON()
### PHP Version

8.4

### CodeIgniter4 Version

7.4.1

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

fpm-fcgi

### Environment

development

### Database

MySQL 5.6

### What happened?

After upgrading from CI4 4.7.0 to 4.7.1, all POST requests with Content-Type: application/json fail when calling $this->request->getJSON().
The CSRF filter modifies $request->body, URL-encoding the raw JSON string. This causes json_decode() to fail with "Failed to parse JSON string. Error: Syntax error".

Debug output proving the issue:
```
php://input (raw, untouched — correct):
  length: 462
  content: {"entity_type":"pages","uuid":"171354f4-..."}

$request->getBody() (after CSRF filter ran — corrupted):
  length: 643
  content: %7B%22entity_type%22%3A%22pages%22%2C%22uuid%22%3A%22171354f4-...
```
php://input contains valid JSON (462 bytes).
$request->getBody() returns the same data but URL-encoded (643 bytes), ending with =.
This indicates the CSRF filter treats the JSON body as a form field key and runs it through URL encoding (likely via parse_str() or similar).
This worked correctly in 4.7.0 — the CSRF filter did not alter the body of application/json requests.

### Steps to Reproduce

Fresh CI4 4.7.1 install (or upgrade from 4.7.0)
Enable CSRF filter globally in app/Config/Filters.php:

```
public array $globals = [
    'before' => [
        'csrf',
    ],
];

```
Create a simple controller:

```
<?php

namespace App\Controllers;

use CodeIgniter\Controller;

class ApiTest extends Controller
{
    public function save()
    {
        $rawInput = file_get_contents('php://input');
        $body     = $this->request->getBody();

        log_message('debug', 'php://input length: ' . strlen($rawInput));
        log_message('debug', 'getBody() length: '   . strlen($body ?? ''));
        log_message('debug', 'php://input first 100: ' . substr($rawInput, 0, 100));
        log_message('debug', 'getBody() first 100: '   . substr($body ?? '', 0, 100));

        // Throws: "Failed to parse JSON string. Error: Syntax error"
        $data = $this->request->getJSON(true);

        return $this->response->setJSON(['success' => true, 'data' => $data]);
    }
}
```

Add route:

`$routes->post('api/test', 'ApiTest::save');`

Send a JSON POST request with a valid CSRF token in the header:

```
fetch('/api/test', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'X-CSRF-TOKEN': csrfToken,
        'X-Requested-With': 'XMLHttpRequest'
    },
    body: JSON.stringify({ name: 'test', value: 'hello world' })
});
```

Result: 500 error — Failed to parse JSON string. Error: Syntax error
Logs confirm: getBody() returns a URL-encoded string instead of raw JSON.

### Expected Output

$this->request->getJSON() should return the decoded JSON object, identical to:
`json_decode(file_get_contents('php://input'));`
The CSRF filter should not modify $request->body when the Content-Type is application/json. The CSRF token should be read from the X-CSRF-TOKEN header — which is the standard approach for AJAX/JSON requests — without altering the request body.
In 4.7.0, this worked correctly: the body was preserved as raw JSON after the CSRF filter ran.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes a regression in CSRF verification introduced in #9969.

When the CSRF token was sent via the `X-CSRF-TOKEN` header, the CSRF filter could still parse the raw request body as form data and rewrite valid JSON into a URL-encoded string. As a result, `IncomingRequest::getJSON()` failed for `application/json` requests.

I am not sure whether this should be patched in 4.7.1 or included in 4.7.2.

Fixes #10063

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value (without duplication)
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Security/Security.php [hunk 1]
```diff
@@ -307,6 +307,11 @@ private function removeTokenInRequest(IncomingRequest $request): void
 
         // If the token is found in form-encoded data, we can safely remove it.
         parse_str($body, $result);
+
+        if (! array_key_exists($tokenName, $result)) {
```
Comment (paulbalandan) [inline system/Security/Security.php]: I'm not sure about this one. Unset doesn't care if the key exists or not, so it'll either be unsetting or no-op.

I looked at the changed lines at my PR and it doesn't change these lines. Should the fix be somewhere in line 301? Remove the property exists check and add that as an inner if instead, returning early if token name is not a json key?

Comment (michalsn) [reply system/Security/Security.php]: See: https://github.com/codeigniter4/CodeIgniter4/blob/v4.7.0/system/Security/Security.php#L292

The regression is not that `unset()` changed behavior. The problem is the new control flow around the JSON branch.

In `4.7.0`, once `json_decode($body)` succeeded, the method stayed on the JSON path, did `unset($json->{$tokenName})`, and wrote JSON back. If the token key was absent, `unset()` was just a no-op, so the body stayed valid JSON.

In `4.7.1`, the code only stays on the JSON path when `property_exists($json, $tokenName)` is `true`.

Comment (michalsn) [reply system/Security/Security.php]: Sorry - I understand now what you meant. I've sent the changes as suggested.

**Review by paulbalandan — APPROVED** [review]
Thanks! I'll release a patch tomorrow at the earliest.

**Review by samsonasik — APPROVED** [review]

**Comment by paulbalandan** [comment]
thank you, @michalsn
