### PR TITLE
fix: initialize standalone toolbar

### LINKED ISSUE #9949: Bug: Standalone Debugbar is not properly initialized
### PHP Version

8.5

### CodeIgniter4 Version

4.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Environment

development

### Database

MySQL 8

### What happened?

When processing non-HTML requests, the Debugbar attaches special headers such as `Debugbar-Link`, which provide a URL to render the Debugbar in a separate request.

Although the Debugbar interface is rendered when visiting that URL, it is not fully initialized, which prevents any interaction with it.

### Steps to Reproduce

1. Add the following route:
```php
// app/Config/Routes.php
$routes->get('ajax', 'Home::ajax');
```
2. Add this method to Home controller:
```php
// app/Controllers/Home.php
public function ajax()
{
    $this->response->setJSON([]);
}
```
3. Add the following script to `welcome_message.php`:
```html
<script>
    fetch('/ajax', {
        headers: {
            'Accept': 'application/json',
            'X-Requested-With': 'XMLHttpRequest'
        }
    })
</script>
```

4. Open Developer Tools and inspect the Network tab.
5. Open the main page in the browser.
6. Check the response headers of the `/ajax` request and look for the `Debugbar-Link` header.
7. Copy the URL from `Debugbar-Link` and open it in a new tab.

The Debugbar is displayed, but it is not interactive because it is not properly initialized.

### Expected Output

The Debugbar should be fully interactive, just as it is when rendered within a standard HTML response.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes a bug where the Debug Toolbar loaded from `?debugbar_time=...` (via `Debugbar-Link` headers for AJAX/non-HTML responses) appeared but was not interactive.

The fix adds a dedicated standalone bootstrap script for this mode, while keeping `toolbar.js` focused on core toolbar behavior. It also provides a `loadDoc()` fallback only when the main loader flow is absent, so the History section keeps working on standalone toolbar pages.

Fixes #9949

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value (without duplication)
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Debug/Toolbar/Views/toolbar.js [hunk 1]
```diff
@@ -8,7 +8,8 @@ var ciDebugBar = {
     icon: null,
 
     init: function () {
-        this.toolbarContainer = document.getElementById("toolbarContainer");
+        // Standalone debugbar pages do not have #toolbarContainer, use body as fallback.
+        this.toolbarContainer = document.getElementById("toolbarContainer") || document.body;
```
Comment (datamweb) [inline system/Debug/Toolbar/Views/toolbar.js]: `ciDebugBar.init()` assumes that `#toolbarContainer` exists for both JavaScript and CSS theme handling, but on standalone debugbar pages (**?debugbar_time=...**) this element is missing. Falling back to `document.body` avoids errors, however without assigning the expected ID the existing CSS no longer matches, so the theme toggle appears non-functional.
```suggestion
        this.toolbarContainer = document.getElementById("toolbarContainer");
        if (!this.toolbarContainer) {
            this.toolbarContainer = document.body;
            if (!document.body.id) {
                document.body.id = "toolbarContainer";
            }
        }
```

**Review by datamweb — CHANGES_REQUESTED** [review]

File: system/Debug/Toolbar/Views/toolbar.js (hunk 1 above)
Comment (michalsn) [reply system/Debug/Toolbar/Views/toolbar.js]: You're right about the theme toggler - I'll fix that. But I'll keep standalone bootstrapping in a separate file to preserve clear responsibility boundaries.

Comment (datamweb) [reply system/Debug/Toolbar/Views/toolbar.js]: Appreciate you taking the time to explain your reasoning.

**Review by datamweb — APPROVED** [review]
LGTM!
In general, many of the existing issues in the debugging tools seem to stem from insufficient test coverage as well, which might be worth addressing over time.

**Review by paulbalandan — APPROVED** [review]

**Comment by michalsn** [comment]
Thank you for the reviews!
