### PR TITLE
Fix routes options to be recognizable via used HTTP request method

### LINKED ISSUE #3700: Bug: getRoutesOptions return wrong when I have >2 routes has same name, but different method (HTTPVerb)
//my routes

`$routes->get('product/add', 	'App\Product::add', ['as' => 'app_product_add']);`
`$routes->post('product/add', 'App\Product::add_ajax', ['as' => 'app_product_add_ajax']);`

//my function 
`$router  = \Config\Services::router();`
`$match  = $router->getMatchedRoute(); // => IT'S OK`
`$options = $router->getMatchedRouteOptions(); //=> WRONG BY METHOD`

$options alway is: `['as' => 'app_product_add_ajax']`
I want setMethod() and default method by current request in here for return right options

How can't I hot fix this bug?

Help me.
Thanks

### LINKED ISSUE #3733: Bug: route filters don't apply for different methods
**Direction**
same route filter is applied for different method

**Describe the bug**
for e.g.
~~~~
$routes->get('', AdminController@index, ['filter' => 'permission:index']);
$routes->delete('', AdminController@index, ['filter' => 'permission:delete]);
~~~~
If I call either method I will get filter params as 'delete' not 'index' even for get requests.

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
Route filter

**Expected behavior, and steps to reproduce if appropriate**
I index request is called route parameters should be index.

**Context**
 - OS:Ubuntu
 - Web server: apache2
 - PHP version : 7.3

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes routes options to be recognizable via used HTTP request method. Right now routes options are shared - one instance per route. It leads to problems like: wrong named route name returned or firing incorrect filter.

I don't think this will introduce any BC, rather will fix buggy behavior, but if anyone notices the problem please let me know.

Fixes #3700 
Fixes #3733

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] N/A User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Router/RouteCollection.php [hunk 1]
```diff
@@ -558,12 +558,15 @@ public function getRoutes($verb = null): array
 	 * Returns one or all routes options
 	 *
 	 * @param string $from
+	 * @param string $verb
```
Comment (samsonasik) [inline system/Router/RouteCollection.php:561]:
```suggestion
       * @param string|null $verb
```

File: system/Router/RouteCollection.php [hunk 2]
```diff
@@ -1285,12 +1288,15 @@ protected function localizeRoute(string $route) :string
 	 * Checks a route (using the "from") to see if it's filtered or not.
 	 *
 	 * @param string $search
+	 * @param string $verb
```
Comment (samsonasik) [inline system/Router/RouteCollection.php:1291]:
```suggestion
       * @param string|null $verb
```

File: system/Router/RouteCollection.php [hunk 3]
```diff
@@ -1306,17 +1312,15 @@ public function isFiltered(string $search): bool
 	 * has a filter of "role", with parameters of ['admin', 'manager'].
 	 *
 	 * @param string $search
+	 * @param string $verb
```
Comment (samsonasik) [inline system/Router/RouteCollection.php:1315]:
```suggestion
       * @param string|null $verb
```

File: system/Router/RouteCollection.php [hunk 4]
```diff
@@ -1582,4 +1586,35 @@ public function resetRoutes()
 		}
 	}
 
+	//--------------------------------------------------------------------
+
+	/**
+	 * Load routes options based on verb
+	 *
+	 * @param string $verb
```
Comment (samsonasik) [inline system/Router/RouteCollection.php:1594]:
```suggestion
       * @param string|null $verb
```

**Review by MGatner — CHANGES_REQUESTED** [review]
I like this. I agree with @samsonasik's changes, also... I know `getRoutes()` has an unspecified variable type on `$verb` but other things will break if it is not `string|null` so I think we should go ahead and update the function declaration to be consistent.

File: system/Router/RouteCollection.php [hunk 5]
```diff
@@ -1582,4 +1586,35 @@ public function resetRoutes()
...
+	 *
+	 * @return array
+	 */
+	protected function loadRoutesOptions(string $verb = null): array
+	{
+		if (empty($verb))
+		{
+			$verb = $this->getHTTPVerb();
+		}
```
Comment (paulbalandan) [inline system/Router/RouteCollection.php:1603]:
```suggestion
	$verb = $verb ?: $this->getHTTPVerb();
```

**Comment by michalsn** [comment]
Thanks for your code suggestions guys.

**Review by MGatner — APPROVED** [review]

**Comment by element-code** [comment]
👍 i was writing a bug report just at this moment and saw the merge while digging for the buggy code 🎆
