### PR TITLE
docs: fix singular table names in API guide's `withAuthorInfo()` method

### LINKED ISSUE #10057: Documentation inconsistency: singular vs plural table names in API guide
### PHP Version

8.3

### CodeIgniter4 Version

4.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Environment

development

### Database

Documentation inconsistency: singular vs plural table names in API guide

## Affected pages:
https://codeigniter.com/user_guide/guides/api/database-setup.html
https://codeigniter.com/user_guide/guides/api/controller.html
## Description:
The API guide contains an inconsistency between the Database Setup page and the Controller page when referring to table names.
On the Database Setup page, the migrations create tables using plural names

However, on the Controller page, the withAuthorInfo() method in BookModel uses singular table names in both the select() and join():
```
public function withAuthorInfo()
{
    return $this
        ->select('book.*, author.name as author_name')
        ->join('author', 'book.author_id = author.id');
}
````

### Steps to Reproduce

Follow the guide for rest api

### Expected Output

Update the guide to use "correct" plural table names or update the migration =) 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AlexRasch**
**Description**
The BookModel::withAuthorInfo() method in the Controller guide uses singular table names (book, author) instead of the plural names (books, authors) created in the Database Setup migration. This updates the method to use the correct plural table names for consistency across the API guide.

Fixes #10057

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value (without duplication)
- [ ] Unit testing, with >80% coverage
- [X] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by michalsn** [comment]
@AlexRasch Please run `composer cs-fix` and send the updated code.

**Comment by neznaika0** [comment]
We talked about it. Many people refer to tables in the singular. For the API too. In the framework, it is usually in the plural, so there were disagreements.

**Comment by michalsn** [comment]
The fix is valid. Since the tables were created using plural names, we should refer to them accordingly. This is part of the same guide. See the linked issue.

File: user_guide_src/source/guides/api/code/013.php [hunk 1]
```diff
@@ -15,8 +15,8 @@ class BookModel extends Model
      */
     public function withAuthorInfo()
     {
-        return $this
-            ->select('book.*, author.id as author_id, author.name as author_name')
-            ->join('author', 'book.author_id = author.id');
+          return $this
```
Comment (paulbalandan) [inline user_guide_src/source/guides/api/code/013.php]:
```suggestion
            return $this
```

**Review by michalsn — APPROVED** [review]

**Comment by michalsn** [comment]
Thank you @AlexRasch

**Comment by vini123** [comment]
虚幻之物对应着冥冥之路！：《羽》
