### PR TITLE
 Fix Controller use validate bug Fixes #1419

### LINKED ISSUE #1419: Controller helper Form validate('groupname') error with rules group
---
name: Bug report
about: Controller helper

---
**Describe the bug**
From Documentation:
Docs » Controllers and Routing » Controllers
Validating $_POST data

if (! $this->validate('signup'))

I get this error:
Argument 1 passed to CodeIgniter\Validation\Validation::setRules() must be of the type array, string given

Config\Validation
public $signup = [
        'username'     => 'required',
        'password'     => 'required',
        'pass_confirm' => 'required|matches[password]',
        'email'        => 'required|valid_email'
    ];
public $signup_errors = [
        'username' => [
            'required'    => 'You must choose a username.',
        ],
        'email'    => [
            'valid_email' => 'Please check the Email field. It does not appear to be valid.'
        ]
    ];

**CodeIgniter 4 version**
CodeIgniter 4.0.0 alpha.2

**Context**
 - OS: [e.g. MAC OS 10.14]
 - Web server [e.g. Apache]
 - PHP version [e.g. 7.2.8]

### PR DESCRIPTION
**Pull request by bangbangda**
**Description**

- Fix Controller use validate bug Fixes #1419
- Fix user guide error for controller.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Controller.php [hunk 1]
```diff
@@ -175,15 +179,37 @@ protected function loadHelpers()
...
+
+			// If the rule wasn't found in the \Config\Validation, we
+			// should throw an exception so the developer can find it.
+			if (! isset($validation->$rules))
+			{
+				throw ValidationException::forRuleNotFound($rules);
+			}
+
+			// If no error message is defined, use the error message in the Config\Validation file
+			if (count($messages) === 0)
```
Comment (samsonasik) [inline system/Controller.php]: use truthy check `if (! $messages)` for better performance: 

```suggestion
			if (! $messages)
```

Comment (bangbangda) [reply system/Controller.php]: Updated.thank you.
