### PR TITLE
fix: Hardcoded CSP Nonce Tags in ResponseTrait

### LINKED ISSUE #9935: Bug: Hardcoded CSP Nonce Tags in ResponseTrait
### PHP Version

8.4, 8.3

### CodeIgniter4 Version

All versions with CSP Placeholders

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Environment

production, development

### Database

N/A

### What happened?

In `ResponseTrait::send()` method, when CSP is disabled, the code uses hardcoded nonce tag values to remove placeholders from the response body:
https://github.com/codeigniter4/CodeIgniter4/blob/1b413583f26240651b9a95a303e3c161af094273/system/HTTP/ResponseTrait.php#L370-L374

However, these nonce tags are configurable in `ContentSecurityPolicy`:
```php
// In system/HTTP/ContentSecurityPolicy.php
protected $styleNonceTag = '{csp-style-nonce}';
protected $scriptNonceTag = '{csp-script-nonce}';

// Users can customize in app/Config/ContentSecurityPolicy.php
public string $styleNonceTag = '{my-own-csp-style-nonce}';
public string $scriptNonceTag = '{my-own-csp-script-nonce}';
```

When CSP was enabled earlier and these tags were used, but due to some reason, CSP is disabled, then the custom CSP tags aren't replaced and the rendered HTML will have custom tags.

### Steps to Reproduce

User customizes nonce tags but temporarily CSP is disabled (as recommended in docs for security):
```php
// app/Config/ContentSecurityPolicy.php
public string $scriptNonceTag = '{custom-secure-script-tag}';
public string $styleNonceTag = '{custom-secure-style-tag}';
public bool $CSPEnabled = false;
```

HTML template uses custom tags:
```html
<script {custom-secure-script-tag}>console.log('test')</script>
```

**Result:** The custom tags remain in the final HTML output because ResponseTrait only looks for the hardcoded default tags!

### Expected Output

The custom tags should be removed from the final HTML output.

### Anything else?

Its not a big problem, as there are no immediate security risks.

I will send PR for this.
Just wanna confirm the bug from project maintainers.

### PR DESCRIPTION
**Pull request by patel-vansh**
**Description**
This PR fixes #9935.

Created one method in `system/HTTP/ContentSecurityPolicy.php` to clear all nonce placeholders.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value (without duplication)
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/HTTP/ContentSecurityPolicy.php [hunk 1]
```diff
@@ -1052,4 +1052,9 @@ public function clearDirective(string $directive): void
 
         $this->{$this->directives[$directive]} = [];
     }
+
+    public function clearNoncePlaceholders(string $text): string
```
Comment (paulbalandan) [inline system/HTTP/ContentSecurityPolicy.php]: - This can go instead in the generateNonces method in the preg_replace_callback so that if $CSPEnabled is false it just returns `''`. 
- In `buildHeaders`, if CSP is disabled, just return
- In ResponseTrait, remove the conditional and retain the finalize call.

File: tests/system/HTTP/ContentSecurityPolicyTest.php [hunk 2]
```diff
@@ -937,4 +937,67 @@ public function testClearDirective(): void
         $this->assertNotContains('report-uri http://example.com/csp/reports', $directives);
         $this->assertNotContains('report-to default', $directives);
     }
+
+    public function testClearNoncePlaceholdersWithDefaultTags(): void
```
Comment (paulbalandan) [inline tests/system/HTTP/ContentSecurityPolicyTest.php]: Remove these tests down and replace with the ones you have in ResponseTest but tailor it to be like in the majority of the tests here.

**Review by paulbalandan — COMMENTED** [review]
The tests don't make sense. You should be testing instead the behavior when the response is sent when CSP is not enabled.

File: system/HTTP/ContentSecurityPolicy.php (hunk 1 above)
Comment (patel-vansh) [reply system/HTTP/ContentSecurityPolicy.php]: Done.

File: tests/system/HTTP/ContentSecurityPolicyTest.php (hunk 2 above)
Comment (patel-vansh) [reply tests/system/HTTP/ContentSecurityPolicyTest.php]: Done.

**Comment by michalsn** [comment]
@patel-vansh Please rebase to resolve conflicts.

**Comment by patel-vansh** [comment]
@michalsn Done.

File: tests/system/HTTP/ResponseTest.php [hunk 3]
```diff
@@ -577,4 +578,124 @@ public function testPretendOutput(): void
...
+        $response = new Response($config);
+        $response->pretend(true);
+
+        $body = '<html><script {csp-script-nonce}>console.log("test")</script><style {csp-style-nonce}>.test{}</style></html>';
+        $response->setBody($body);
+
+        ob_start();
+        $response->send();
+        $actual = ob_get_contents();
+        ob_end_clean();
```
Comment (paulbalandan) [inline tests/system/HTTP/ResponseTest.php]: Can you do `ob_get_clean()` instead?

File: tests/system/HTTP/ResponseTest.php [hunk 4]
```diff
@@ -577,4 +578,124 @@ public function testPretendOutput(): void
...
+
+        // Nonce placeholders should be removed when CSP is disabled
+        $this->assertStringNotContainsString('{csp-script-nonce}', (string) $actual);
```
Comment (paulbalandan) [inline tests/system/HTTP/ResponseTest.php]: Add an `assertIsString()` test for the `$actual` so you don't need the string cast here down.

File: tests/system/HTTP/ResponseTest.php [hunk 5]
```diff
@@ -577,4 +578,124 @@ public function testPretendOutput(): void
...
+        $cspProperty = $reflection->getProperty('CSP');
+        $cspProperty->setValue($response, new ContentSecurityPolicy($cspConfig));
+
+        $body = '<html><script {custom-script-tag}>test()</script><style {custom-style-tag}>.x{}</style></html>';
+        $response->setBody($body);
+
+        ob_start();
+        $response->send();
+        $actual = ob_get_contents();
+        ob_end_clean();
```
Comment (paulbalandan) [inline tests/system/HTTP/ResponseTest.php]: Use `ob_get_clean()` as shortcut?

File: tests/system/HTTP/ResponseTest.php [hunk 6]
```diff
@@ -577,4 +578,124 @@ public function testPretendOutput(): void
...
+
+        // Custom nonce placeholders should be removed when CSP is disabled
+        $this->assertStringNotContainsString('{custom-script-tag}', (string) $actual);
```
Comment (paulbalandan) [inline tests/system/HTTP/ResponseTest.php]: Add `assertIsString` to remove the string cast.

File: tests/system/HTTP/ResponseTest.php [hunk 7]
```diff
@@ -577,4 +578,124 @@ public function testPretendOutput(): void
...
+
+        $body = '';
+        $response->setBody($body);
+
+        ob_start();
+        $response->send();
+        $actual = ob_get_contents();
+        ob_end_clean();
+
+        $this->assertSame('', (string) $actual);
```
Comment (paulbalandan) [inline tests/system/HTTP/ResponseTest.php]: Use `ob_get_clean` and add `assertIsString`.

File: tests/system/HTTP/ResponseTest.php [hunk 8]
```diff
@@ -577,4 +578,124 @@ public function testPretendOutput(): void
...
+        $body = '<html><head><title>Test</title></head><body><p>No placeholders here</p></body></html>';
+        $response->setBody($body);
+
+        ob_start();
+        $response->send();
+        $actual = ob_get_contents();
+        ob_end_clean();
+
+        // Body should be unchanged when there are no placeholders and CSP is disabled
+        $this->assertSame($body, (string) $actual);
```
Comment (paulbalandan) [inline tests/system/HTTP/ResponseTest.php]: Use `ob_get_clean` and add `assertIsString`.

File: tests/system/HTTP/ResponseTest.php [hunk 9]
```diff
@@ -577,4 +578,124 @@ public function testPretendOutput(): void
...
+        $body = '<html><script {csp-script-nonce}>console.log("test")</script><script {csp-script-nonce}>console.log("test2")</script><style {csp-style-nonce}>.test{}</style><style {csp-style-nonce}>.test2{}</style></html>';
+        $response->setBody($body);
+
+        ob_start();
+        $response->send();
+        $actual = ob_get_contents();
+        ob_end_clean();
+
+        // All nonce placeholders should be removed when CSP is disabled
+        $this->assertStringNotContainsString('{csp-script-nonce}', (string) $actual);
```
Comment (paulbalandan) [inline tests/system/HTTP/ResponseTest.php]: Use `ob_get_clean` and add `assertIsString`.

File: system/HTTP/ResponseTrait.php [hunk 10]
```diff
@@ -367,11 +367,7 @@ public function send()
     {
         // If we're enforcing a Content Security Policy,
         // we need to give it a chance to build out it's headers.
-        if ($this->CSP->enabled()) {
-            $this->CSP->finalize($this);
-        } else {
-            $this->body = str_replace(['{csp-style-nonce}', '{csp-script-nonce}'], '', $this->body ?? '');
-        }
+        $this->CSP->finalize($this);
```
Comment (paulbalandan) [inline system/HTTP/ResponseTrait.php:370]: With this change, if CSP is disabled and auto-nonce is also disabled, then replacement with `''` would not happen. Can you add a test where `$CSPEnabled` is false and `$autoNonce` is also false where the response body will still be correctly replaced with empty strings on the tags?

Comment (patel-vansh) [reply system/HTTP/ResponseTrait.php:370]: If `$autoNonce` is disabled, then wouldn't be expected behaviour that no replacing is done? I mean, if user sets `$autoNonce` to `false`, then they won't be adding `{csp-style-nonce}` in the first place isn't it?

File: tests/system/HTTP/ResponseTest.php (hunk 9 above)
Comment (patel-vansh) [reply tests/system/HTTP/ResponseTest.php]: Done

File: tests/system/HTTP/ResponseTest.php (hunk 8 above)
Comment (patel-vansh) [reply tests/system/HTTP/ResponseTest.php]: Done

File: tests/system/HTTP/ResponseTest.php (hunk 6 above)
Comment (patel-vansh) [reply tests/system/HTTP/ResponseTest.php]: Done

File: tests/system/HTTP/ResponseTest.php (hunk 5 above)
Comment (patel-vansh) [reply tests/system/HTTP/ResponseTest.php]: Done

File: tests/system/HTTP/ResponseTest.php (hunk 4 above)
Comment (patel-vansh) [reply tests/system/HTTP/ResponseTest.php]: Done

File: tests/system/HTTP/ResponseTest.php (hunk 3 above)
Comment (patel-vansh) [reply tests/system/HTTP/ResponseTest.php]: Done.

File: system/HTTP/ResponseTrait.php (hunk 10 above)
Comment (patel-vansh) [reply system/HTTP/ResponseTrait.php:370]: Or, I guess, you mean, if we won't do the replacement, then it will be a breaking change. Then, yeah. You're right. I am adding a else block in `finalize` function.

Comment (patel-vansh) [reply system/HTTP/ResponseTrait.php:370]: But, now, two tests are failing.

https://github.com/codeigniter4/CodeIgniter4/blob/develop/tests/system/HTTP/ContentSecurityPolicyTest.php#L751-L787

Comment (patel-vansh) [reply system/HTTP/ResponseTrait.php:370]: I can't figure it out why these two tests were not failing in older code.

Comment (paulbalandan) [reply system/HTTP/ResponseTrait.php:370]: In previous versions, this is the logic:

1. If CSP is enabled:
     - If autoNonce true, replace tags with actual nonce values
     - If autoNonce false, no replacements made

3. If CSP is disabled:
    - Regardless of autoNonce value, the tags should be replaced by empty strings.

So, this logic should be retained.

Comment (patel-vansh) [reply system/HTTP/ResponseTrait.php:370]: Done.

Comment (paulbalandan) [reply system/HTTP/ResponseTrait.php:370]: I think this can be handled all inside `generateNonces` method inside CSP class.

Typing on phone, but this is what I have in mind.
1. finalize method - remove the if block, generateNonces method is called always
2. generateNonces method - if autoNonce is false, just return early. then in the preg_replace callback function, do a check if csp is enabled to determine what replacement will be made on the tags

Comment (patel-vansh) [reply system/HTTP/ResponseTrait.php:370]: If I do this, then the 2nd point you told earlier will have problem. We can do like, return early only if CSP is enabled and autoNonce is false. As, generateNonces will be called no matter any combination of CSP and autoNonce is there, so we have to add this AND case there.

Comment (patel-vansh) [reply system/HTTP/ResponseTrait.php:370]: Any other approach coming to your mind?

Comment (paulbalandan) [reply system/HTTP/ResponseTrait.php:370]: Thanks. I will just check this later when I have access to my laptop 👍

File: tests/system/HTTP/ResponseTest.php [hunk 11]
```diff
@@ -577,4 +578,156 @@ public function testPretendOutput(): void
...
+        $cspConfig->scriptNonceTag = '{custom-script-tag}';
+        $cspConfig->styleNonceTag  = '{custom-style-tag}';
+
+        $response = new Response($appConfig);
+        $response->pretend(true);
+
+        // Inject the custom CSP config
+        $reflection  = new ReflectionClass($response);
+        $cspProperty = $reflection->getProperty('CSP');
+        $cspProperty->setValue($response, new ContentSecurityPolicy($cspConfig));
```
Comment (paulbalandan) [inline tests/system/HTTP/ResponseTest.php]: Instead of these lines, call `Services::injectMock` for the `csp` service by injecting the custom CSP instance. Make sure to call that before Response is instantiated.

File: tests/system/HTTP/ResponseTest.php [hunk 12]
```diff
@@ -577,4 +578,156 @@ public function testPretendOutput(): void
...
+        $cspConfig            = new \Config\ContentSecurityPolicy();
+        $cspConfig->autoNonce = false;
+
+        $response = new Response($appConfig);
+        $response->pretend(true);
+
+        // Inject the custom CSP config
+        $reflection  = new ReflectionClass($response);
+        $cspProperty = $reflection->getProperty('CSP');
+        $cspProperty->setValue($response, new ContentSecurityPolicy($cspConfig));
```
Comment (paulbalandan) [inline tests/system/HTTP/ResponseTest.php]: See comment above.

File: tests/system/HTTP/ResponseTest.php (hunk 11 above)
Comment (patel-vansh) [reply tests/system/HTTP/ResponseTest.php]: Done

File: tests/system/HTTP/ResponseTest.php (hunk 12 above)
Comment (patel-vansh) [reply tests/system/HTTP/ResponseTest.php]: Done

**Review by paulbalandan — APPROVED** [review]
Thanks a lot!

**Review by michalsn — APPROVED** [review]
Thank you!

**Comment by paulbalandan** [comment]
Thank you, @patel-vansh
