### PR TITLE
is_unique tried to connect to default database instead of defined in DBGroup.

### LINKED ISSUE #1326: Bug report: Important bug in is_unique with DBGroup  different than defined in $defaultGroup
My database config is:

```

public $defaultGroup = 'defaultZT';

public $defaultZT = ['my old database credentials'];

public $defaultNEW = ['my new database credentials'];


```
and simple model class...

```
class AdminGroupModel extends \CodeIgniter\Model
{
	protected $DBGroup 		= 'defaultNEW';
	protected $table 		= 't_admin_group';
	protected $primaryKey 	= 'agr_identifier';
	protected $returnType 	= 'App\Entities\Admin\AdminGroup';

	protected $allowedFields = [
		'agr_identifier',
		'agr_description'
	];

	protected $validationRules = [
		'agr_identifier' 	=> 'required|min_length[1]|max_length[16]|regex_match[/[0-9a-zA-Z]{1,16}/]|is_unique[t_admin_group.agr_identifier,agr_identifier,{agr_identifier}]',
		'agr_description' 	=> 'required|max_length[512]',
	];
}


```

When I am trying to save   (new \AdminGroupModel)->save($entity); i get an exception:

> mysqli_sql_exception #1146
> Table 'myolddatabasename.t_admin_group' doesn't exist 

which obviously means it tried to connect my old database.... i noticed that **validation rule is_unique** causes this exception.

### PR DESCRIPTION
**Pull request by nowackipawel**
Fixes #1326

### CODE REVIEW

File: system/Validation/Validation.php [hunk 1]
```diff
@@ -123,10 +123,13 @@ public function __construct($config, RendererInterface $view)
 	 *
 	 * @return bool
 	 */
-	public function run(array $data = null, string $group = null): bool
+	public function run(array $data = null, string $group = null, ?string $db_group = null): bool
```
Comment (lonnieezell) [inline system/Validation/Validation.php]: no need for the optional signifier when using null. Prefer not to have those.
