### PR TITLE
fix: escape CSP nonce attributes in JSON responses

### LINKED ISSUE #9934: Bug: CSP nonce replacement corrupts JSON responses in AJAX requests
### PHP Version

8.2, 8.3, 8.4

### CodeIgniter4 Version

All versions with CSP support

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Environment

development

### Database

_No response_

### What happened?

When Content Security Policy (CSP) is enabled and an exception occurs during an AJAX request, the JSON error response becomes corrupted and causes JSON parsing errors on the client side.

The response contains malformed JSON with improperly escaped quotes, looking something like:
```json
{"script-nonce-tag":"nonce="ads45adf4g2154df""}
```
This results in JavaScript JSON.parse() errors like:
- SyntaxError: Unexpected token n in JSON at position X
- JSON Parse error: Unrecognized token

The issue occurs when:
- CSP is enabled in the application (`$CSPEnabled = true`)
- An exception is thrown during an AJAX request (with Accept: application/json header)
- The error response contains CSP nonce placeholder tags (e.g., from debug output or error traces)
- The CSP generateNonces() method replaces these placeholders inside the JSON string values, breaking the JSON format

### Steps to Reproduce

1. **Enable CSP in your application:**
   ```php
   // app/Config/ContentSecurityPolicy.php
   public bool $CSPEnabled = true;
   ```

2. **Create a controller that throws an exception during AJAX:**
   ```php
   // app/Controllers/Test.php
   namespace App\Controllers;

   class Test extends BaseController
   {
       public function ajaxError()
       {
           // This will trigger an exception
           $array = [];
           echo $array['undefined_key']; // Undefined array key error
       }
   }
   ```

3. **Make an AJAX request to the endpoint:**
   ```javascript
   fetch('/test/ajaxError', {
       headers: {
           'Accept': 'application/json',
           'X-Requested-With': 'XMLHttpRequest'
       }
   })
   .then(response => response.json())
   .catch(error => {
       console.error('JSON Parse Error:', error);
       // This error will be thrown due to malformed JSON
   });
   ```

4. **Observe the error:**
   - The browser console shows a JSON parsing error
   - Inspecting the raw response shows corrupted JSON with `nonce="..."` inside string values
   - The response body contains something like: `{"error":"...","trace":"...nonce=\"abc123\"..."}`

### Expected Output

The JSON error response should remain valid JSON that can be properly parsed by the client.

**Expected behavior:**
```json
{
  "error": "Undefined array key",
  "message": "...",
  "trace": [
    "at line 10 in file.php",
    "..."
  ]
}
```

The CSP nonce replacement logic should:
1. **Only** replace nonce placeholders in HTML responses (`Content-Type: text/html`)
2. **Not** replace or corrupt nonce placeholders in JSON, XML, or other structured data responses
3. Either remove the placeholders or leave them as-is in non-HTML responses

### Root Cause

The bug is in `system/HTTP/ContentSecurityPolicy.php` in the `generateNonces()` method (around line 907).

The method performs a blind regex replacement of `{csp-script-nonce}` and `{csp-style-nonce}` placeholders on **all response bodies**, regardless of the Content-Type. This breaks JSON and XML responses.

```php
// Current buggy code
protected function generateNonces(ResponseInterface $response)
{
    $body = (string) $response->getBody();
    if ($body === '') {
        return;
    }

    // This replaces nonces in ALL content types, including JSON
    $pattern = sprintf('/(%s|%s)/', preg_quote($this->styleNonceTag, '/'), preg_quote($this->scriptNonceTag, '/'));
    $body = preg_replace_callback($pattern, function ($match): string {
        $nonce = $match[0] === $this->styleNonceTag ? $this->getStyleNonce() : $this->getScriptNonce();
        return "nonce=\"{$nonce}\""; // This breaks JSON!
    }, $body);

    $response->setBody($body);
}
```

### Suggested Fix

Add a Content-Type check to only perform nonce replacement for HTML responses:

```php
protected function generateNonces(ResponseInterface $response)
{
    $body = (string) $response->getBody();
    if ($body === '') {
        return;
    }

    // Check Content-Type header
    $contentType = $response->getHeaderLine('Content-Type');

    // Only replace nonces in HTML content, not JSON/XML/etc
    if ($contentType !== '' && ! str_contains($contentType, 'text/html')) {
        // For non-HTML responses, just remove the placeholders
        $body = str_replace([$this->styleNonceTag, $this->scriptNonceTag], '', $body);
        $response->setBody($body);
        return;
    }

    // For HTML: replace placeholders with actual nonces (existing behavior)
    $pattern = sprintf('/(%s|%s)/', preg_quote($this->styleNonceTag, '/'), preg_quote($this->scriptNonceTag, '/'));
    $body = preg_replace_callback($pattern, function ($match): string {
        $nonce = $match[0] === $this->styleNonceTag ? $this->getStyleNonce() : $this->getScriptNonce();
        return "nonce=\"{$nonce}\"";
    }, $body);

    $response->setBody($body);
}
```

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes a bug where `ContentSecurityPolicy::generateNonces()` could corrupt the JSON response body.

The method now detects `application/json` Content-Type responses and properly escapes double quotes in nonce attribute replacements, preventing malformed JSON.

Fixes #9934

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value (without duplication)
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: tests/system/HTTP/ContentSecurityPolicyTest.php [hunk 1]
```diff
@@ -937,4 +937,38 @@ public function testClearDirective(): void
...
+
+        $this->response->setBody($body);
+        $this->csp->finalize($this->response);
+
+        $result = $this->response->getBody();
+
+        $this->assertMatchesRegularExpression('/<style nonce="[A-Za-z0-9+\/=]+">/', $result);
+        $this->assertMatchesRegularExpression('/<script nonce="[A-Za-z0-9+\/=]+">/', $result);
+        $this->assertStringNotContainsString('{csp-style-nonce}', (string) $result);
+        $this->assertStringNotContainsString('{csp-script-nonce}', (string) $result);
```
Comment (paulbalandan) [inline tests/system/HTTP/ContentSecurityPolicyTest.php]: Add a `$this->assertIsString()` on the `$result` so that the cast is unneeded.

File: tests/system/HTTP/ContentSecurityPolicyTest.php [hunk 2]
```diff
@@ -937,4 +937,38 @@ public function testClearDirective(): void
...
+    {
+        $data = json_encode(['html' => '<script {csp-script-nonce}>alert(1)</script>']);
+
+        $this->response->setContentType('application/json');
+        $this->response->setBody($data);
+        $this->csp->finalize($this->response);
+
+        $result = $this->response->getBody();
+        $parsed = json_decode($result, true);
+
```
Comment (paulbalandan) [inline tests/system/HTTP/ContentSecurityPolicyTest.php:971]: Can you also assert that `json_last_error()` is `JSON_ERROR_NONE`?

File: user_guide_src/source/changelogs/v4.7.1.rst [hunk 3]
```diff
@@ -32,6 +30,8 @@ Deprecations
 Bugs Fixed
 **********
 
+- **ContentSecurityPolicy:** Fixed a bug where ``generateNonces()`` corrupted JSON responses by replacing CSP nonce placeholders with unescaped double quotes. The method now automatically JSON-escapes nonce attributes when the response Content-Type is JSON.
```
Comment (paulbalandan) [inline user_guide_src/source/changelogs/v4.7.1.rst]:
```suggestion
- **ContentSecurityPolicy:** Fixed a bug where ``generateNonces()`` produces corrupted JSON responses by replacing CSP nonce placeholders with unescaped double quotes. The method now automatically JSON-escapes nonce attributes when the response Content-Type is JSON.
```

File: tests/system/HTTP/ContentSecurityPolicyTest.php (hunk 1 above)
Comment (michalsn) [reply tests/system/HTTP/ContentSecurityPolicyTest.php]: Done

File: tests/system/HTTP/ContentSecurityPolicyTest.php (hunk 2 above)
Comment (michalsn) [reply tests/system/HTTP/ContentSecurityPolicyTest.php:971]: Done.

File: user_guide_src/source/changelogs/v4.7.1.rst (hunk 3 above)
Comment (michalsn) [reply user_guide_src/source/changelogs/v4.7.1.rst]: Done.

**Review by paulbalandan — APPROVED** [review]

**Review by datamweb — APPROVED** [review]

**Comment by michalsn** [comment]
Thank you @paulbalandan and @datamweb
